#!/bin/bash

# Prompt user to select an option
select option in "Search for files by name" "Search for files by owner" "Search for files by modification time" "Exit"
do
    case $option in
        # Option 1: Search for files by name
        "Search for files by name")
            echo "Enter the file name to search for:"
            read filename
            echo "Enter the directory path to search in:"
            read directory
            find "$directory" -name "$filename"
            ;;

        # Option 2: Search for files by owner
        "Search for files by owner")
            echo "Enter the username to search for:"
            read username
            echo "Enter the directory path to search in:"
            read directory
            find "$directory" -user "$username"
            ;;

        # Option 3: Search for files by modification time
        "Search for files by modification time")
            echo "Enter the number of days (e.g. 7) to search for files modified more than:"
            read days
            echo "Enter the directory path to search in:"
            read directory
            find "$directory" -mtime +"$days"
            ;;

        # Option 4: Exit the script
        "Exit")
            exit
            ;;
        
        # Invalid option selected
        *)
            echo "Invalid option selected"
            ;;
    esac
done
